spring.config.import=optional:classpath:application-local.properties
spring.application.name=cloud-storage
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
minio.endpoint=http://localhost:9000
minio.bucket=user-files
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=500MB
server.tomcat.max-part-count=1000